export const LOGIN = 'LOGIN';
export const AUTENTICADO = 'AUTENTICADO';
export const NOT_AUTENTICADO = 'NOT_AUTENTICADO';
export const CERRAR_SESION = 'CERRAR_SESION';

// LISTADO DE EVALUACIONES
export const LISTAR_EVALUACIONES = 'LISTAR_EVALUACIONES';
export const LISTAR_FILTRADOS = 'LISTAR_FILTRADOS';
export const NUMERO_MESES = 'NUMERO_MESES';
